# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative 'vagrant_rancheros_guest_plugin.rb'
require 'ipaddr'

boxes = [
    {
        :name => "control",
        :eth1 => "172.22.101.100",
        :ssh => "2200",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "master",
        :eth1 => "172.22.101.101",
        :ssh => "2201",
        :mem => "2048",
        :cpu => "2"
    },
    {
        :name => "worker",
        :eth1 => "172.22.101.102",
        :ssh => "2202",
        :mem => "2048",
        :cpu => "2"
    }
]

Vagrant.configure(2) do |config|
    config.vm.box = "digitalism/rancher-os"
    config.vm.box_version = "1.5.5"
    config.vm.guest = :linux
    config.ssh.insert_key = false

    # config.vm.provision "file", source: "../keys/id_rsa_rancher.pub", destination: "~/.ssh/authorized_keys"
    # config.vm.provision "file", source: "../keys/id_rsa_rancher", destination: "~/.ssh/id_rsa"
    # config.ssh.private_key_path = ["../keys/id_rsa_rancher", "~/.vagrant.d/insecure_private_key"]
    # config.vm.provision :shell, :inline =>"
    #       chmod 700 ~/.ssh
    #       chmod -R 600 ~/.ssh/*
    #     ", privileged: false


    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.network :forwarded_port, guest: 22, host: opts[:ssh], id: 'ssh'
        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          v.customize ["modifyvm", :id, "--name", opts[:name]]
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        end
        config.vm.hostname = opts[:name]
        config.vm.network :private_network, ip: opts[:eth1], nic_type: "82545EM"
      end
    end

end
