# -*- mode: ruby -*-
# vi: set ft=ruby :
require_relative 'vagrant_rancheros_guest_plugin.rb'
require 'ipaddr'

boxes = [
    {
        :name => "control",
        :eth1 => "172.22.101.100",
        :sshport => "2200",
        :mem => "4096",
        :cpu => "4"
    },
    {
       :name => "master",
       :eth1 => "172.22.101.101",
       :sshport => "2201",
       :mem => "4096",
       :cpu => "4"
    },
    {
       :name => "worker",
       :eth1 => "172.22.101.102",
       :sshport => "2202",
       :mem => "4096",
       :cpu => "2"
    }
]

Vagrant.configure(2) do |config|
    config.vm.box = "chrisurwin/RancherOS"
    config.vm.box_version = "1.5.1"
    config.vm.guest = :linux

    config.ssh.insert_key = false
    config.ssh.private_key_path = ["../keys/id_rsa_terraform_rancher", "~/.vagrant.d/insecure_private_key"]

    config.vm.provision "file", source: "../keys/id_rsa_terraform_rancher.pub", destination: "~/.ssh/authorized_keys"
    config.vm.provision "file", source: "../keys/id_rsa_terraform_rancher", destination: "~/.ssh/id_rsa"
    config.vm.provision :shell, :inline =>"
          chmod 700 ~/.ssh
          chmod -R 600 ~/.ssh/*
        ", privileged: false

    config.vm.synced_folder '.', '/vagrant', disabled: true
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]

        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", opts[:name]]
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
          v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
        config.vm.network :forwarded_port, guest: 22, host: opts[:sshport], id: 'ssh'
        config.vm.network :private_network, ip: opts[:eth1], nic_type: "82545EM"
      end
    end

end
