# -*- mode: ruby -*-
# vi: set ft=ruby :

boxes = [
    {
        :name => "control.javaansehz.cloud",
        :eth1 => "172.22.101.100",
        :sshport => "2200",
        :mem => "4096",
        :cpu => "4"
    },
    {
       :name => "master.javaansehz.cloud",
       :eth1 => "172.22.101.101",
       :sshport => "2201",
       :mem => "4096",
       :cpu => "4"
    },
    {
       :name => "worker.javaansehz.cloud",
       :eth1 => "172.22.101.102",
       :sshport => "2202",
       :mem => "2048",
       :cpu => "2"
    }
]

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.box_version = "20200407.0.0"

    config.vm.synced_folder '.', '/vagrant', disabled: true
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]

        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--name", opts[:name]]
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
          v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        end
        config.vm.provision "ansible" do |ansible|
          ansible.playbook = "ansible/prepare-nodes.yml"
        end
        config.vm.network :forwarded_port, guest: 22, host: opts[:sshport], id: 'ssh'
        config.vm.network :private_network, ip: opts[:eth1], nic_type: "82545EM"
      end
    end

end
