apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-hostbased
  namespace: cattle-system
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: rancher
          servicePort: 80
